version: '3'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest-auth-token
    # volumes:
    #   - ./data:/var/lib/postgresql/data
#   pg-admin:
#     image: dpage/pgadmin4:latest
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@email.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#       PGADMIN_LISTEN_PORT: 5050
#     ports:
#       - 5050:80

# volumes:
#   data:
